name: Status Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install dependencies
        run: |
          bundle install

      - name: Run RuboCop
        run: |
          bundle exec rubocop

      - name: Run RSpec Tests
        run: |
          bundle exec rspec

      - name: Run Cucumber Tests
        run: |
          bundle exec cucumber
